[window]
opacity = 0.60

[general]
import = [
    "~/.config/alacritty/themes/themes/nightfly.toml"
]
live_config_reload = true

[window.padding]
x = 10
y = 10

[colors.primary]
background="#020a1a"

