[[language]]
name = "cpp"
auto-format = true
file-types = ["cpp", "cc", "hh", "hxx", "hpp"]
formatter = { command = "clang-format --style=file:/home/ellimac/.config/helix/clang-format-cxx", args= [ "%{buffer_name}"] }

